apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-cd-api-30
  namespace: tekton-tasks
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
    - name: gitUrl
      value: https://github.com/Acuity-Inc/tech-challenge-ci-cd-api.git
    - name: gitRevision
      value: master
    - name: imageUrl
      value: danieltmcc/tsg-innolab-cicd-api
    - name: imageTag
      value: "1.0"
    - name: pathToYamlFile
      value: manifest.yaml
  serviceAccountName: tekton-sa
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
