apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-cdk-role
  namespace: tekton-tasks
rules:
- apiGroups: ["extensions", "apps", ""]
  resources: ["services", "deployments", "pods","pvc","job"]
  verbs: ["get", "create", "update", "patch", "list", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-cdk-role-binding
  namespace: tekton-tasks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-cdk-role
subjects:
- kind: ServiceAccount
  name: tekton-sa
